# Dependabot config.
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
- package-ecosystem: "github-actions"
	directory: "/"
	schedule:
		interval: "daily"
