
default: all

CXX = g++
CC = gcc
#CC = $(CXX)

CONFIG += ansi
#CONFIG += errwarn
CONFIG += debug
#CONFIG += ultradebug
#CONFIG += fast
#CONFIG += noassert

CxPath = ../cx
BinPath = ../bin
BldPath = protocon

ExeList = protocon satsyn
ExeList := $(addprefix $(BinPath)/,$(ExeList))

include $(CxPath)/include.mk

CXXBldPath = $(PfxBldPath)/protocon-cxx

GluPath = ../glu-2.4
GluIncludePath = $(GluPath)/include

CFLAGS += -I$(GluIncludePath)
CXXFLAGS += $(CFLAGS)
LXXFLAGS += -L$(GluPath) -lcmu -lglu -lcu -lcal -lm

-include deps.mk

all: $(ExeList)

$(BinPath)/protocon: \
	$(addprefix $(BldPath)/, pfmla.o pfmla-glu.o pfmla-bittable.o) \
	$(addprefix $(BldPathCXX)/, main.o inst.o pfmla.o promela.o test.o xnsys.o) \
	$(addprefix $(CxBldPath)/,fileb.o syscx.o bstree.o rbtree.o)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LXXFLAGS)

$(call binexe,satsyn): $(BldPath)/satsyn.o $(BldPath)/xnsys.o \
	$(addprefix $(CxBldPath)/, bstree.o fileb.o ospc.o rbtree.o syscx.o)
	$(CC) $(CFLAGS) -o $@ $^

#$(BldPath)/pfmla-glu.o: $(BldPath)/pfmla-glu.c
#	$(CXX) -c $(CFLAGS) -I$(GluIncludePath) $< -o $@

.PHONY: depend
depend: deps.mk

deps.mk:
	grep '^#include *"' *.cc *.hh *.c *.h \
		| grep -v -e 'mdd\.h' -e 'cx/' \
		| sed -e 's/\(.*\):#include.*"\(.*\)".*/\1: \2/' \
		-e 's:\(.*\.\)\(cc\|hh\)\::$(BldPathCXX)\/\1\2\::' \
		-e 's:\(.*\.\)\(c\|h\)\::$(BldPath)\/\1\2\::' \
		-e 's:\: \(.*\.\)\(cc\|hh\)$$:\: $(BldPathCXX)/\1\2:' \
		-e 's:\: \(.*\.\)\(c\|h\)$$:\: $(BldPath)/\1\2:' \
		> deps.mk

.PHONY: clean
clean:
	rm -fr $(PfxBldPath)
	rm -f $(ExeList)
	rm -f deps.mk

