
cc_binary(
    name = "aperiodic",
    srcs = [
        "aperiodic.cc",
        "uniact.hh",
        "unifile.cc",
        "unifile.hh",
        "//src:namespace.hh",
    ],
    deps = [
        "//src/cx:cx_lib",
        "@lace//src/cx:cx_lib",
    ],
    copts = [
        "-Isrc",
        "-Iexternal/lace/src",
    ],
)

