cc_binary(
    name = "satsyn",
    srcs = [
        "dimacs.h",
        "inst-bit3.h",
        "inst-coloring.h",
        "inst-dijkstra4state.h",
        "inst-dijkstra.h",
        "inst-matching.h",
        "inst-sat3.h",
        "satsyn.c",
        "pla.h",
        "promela.h",
        "xnsys.c",
        "xnsys.h",
    ],
    deps = [
        "//src/cx:cx_lib",
    ],
    copts = ["-Isrc"],
)

