---
name: Docker Image

on:
  push:
    branches: ['deploy']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Bazel Setup
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: '6'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: bazel build -c opt //src:protocon

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: bazel-bin/
        file: pkg/docker/Dockerfile
        push: true
        tags: ghcr.io/protocolconvergence/protocon:latest
