---
name: Bazel
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Cache Setup
      uses: actions/cache@v4
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel

    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: '6'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: bazel build //...

    - name: Test
      # --enable_runfiles is for Windows tests to access data deps.
      run: bazel test --enable_runfiles --test_timeout 300 //...

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: bazel-testlogs-(${{ matrix.platform }})
        path: bazel-testlogs*/**/*


  coverage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: '6'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: >
        bazel coverage
        --instrument_test_targets
        --instrumentation_filter="^//..."
        --combined_report=lcov
        --
        //...

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: bazel-out/_coverage/_coverage_report.dat
